version: "3"

services:
    app:
        image: dumpstr:latest
        build:
            context: .
        container_name: dumpstr_app
        ports:
            - "8000:8000"
        depends_on:
            defaultDB:
                condition: service_healthy
            postgres:
                condition: service_started
        volumes:
            - ./:/app
        command: >
            bash -c "python manage.py wait_for_db &&
                     python manage.py makemigrations &&
                     python manage.py migrate &&
                     python manage.py runserver 0.0.0.0:8000"

        env_file:
            - ./dumpstR/config/.env.dev
    postgres:
        image: postgres:15
        container_name: dumpstr_pgsql
        volumes:
            - psqlDB:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=dumpstrDB
            - POSTGRES_USER=dumpstr
            - POSTGRES_PASSWORD=FJcuf5dhRMQrjj
        restart: always

    defaultDB:
        image: mysql:8
        container_name: dumpstr_mysql
        ports:
            - "3309:3306"
        volumes:
            - mysqlDB:/var/lib/mysql
        environment:
            - MYSQL_USER=dumpstr
            - MYSQL_DATABASE=dumpstrDB
            - MYSQL_PASSWORD=F8YdLl4VwBTPLYo1yyWy
            - MYSQL_ROOT_PASSWORD=FJcuf5dhRMQrjj
        restart: always
        env_file:
            - ./dumpstR/config/.env.dev
        healthcheck:
            test: [
                "CMD","mysqladmin", "-u", "root", "-p${MYSQL_DB_ROOT_PASS}", "ping", "-h", "localhost"
            ]
            timeout: 20s
            retries: 10
    redis:
        image: redis:alpine
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - redisData:/data
    rabbit:
        image: rabbitmq:3-management
        container_name: rabbit-server
        hostname: dumpstr
        ports:
            - "5673:5672"
            - "15673:15672"
        environment:
            RABBIT_ERLANG_COOKIE: "SWQOKDSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: "rabbit"
            RABBITMQ_DEFAULT_PASS: "rabbit"
volumes:
    psqlDB:
    mysqlDB:
    redisData:
