# Generated by Django 4.2.9 on 2024-02-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contactenroll_contacted'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetflixMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.CharField(max_length=20)),
                ('show_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=80)),
                ('cast', models.JSONField()),
                ('country', models.CharField(max_length=100)),
                ('date_added', models.DateField()),
                ('release_year', models.DateField()),
                ('rating', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('listed_in', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
